/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hendryf
 * 14.09.21
 */
public class Calculadora extends javax.swing.JFrame {
    private String number_key = "";
    private String operation_key = "";
    private boolean ce_key = false;
    private boolean c_key = false;
    private boolean equals_key = false;
    
    private String sign1 = "";
    private String sign2 = "";
    private String argument1 = "";
    private String argument2 = "";
    private String operation = "";
    
    private String display1 = "";
    private String display2 = "";
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ce_btn = new javax.swing.JButton();
        c_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        entre_btn = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        por_btn = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        menos_btn = new javax.swing.JButton();
        punto_btn = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        igual_btn = new javax.swing.JButton();
        mas_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(" ");
        jLabel1.setMaximumSize(new java.awt.Dimension(3, 10));
        jLabel1.setMinimumSize(new java.awt.Dimension(3, 55959));
        jPanel1.add(jLabel1);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 4));

        ce_btn.setText("CE");
        ce_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ce_btnActionPerformed(evt);
            }
        });
        jPanel2.add(ce_btn);

        c_btn.setText("C");
        c_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_btnActionPerformed(evt);
            }
        });
        jPanel2.add(c_btn);
        jPanel2.add(jSeparator1);
        jPanel2.add(jSeparator2);

        jPanel3.setLayout(new java.awt.GridLayout(4, 0));

        btn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel3.add(btn7);

        btn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel3.add(btn8);

        btn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel3.add(btn9);

        entre_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entre_btn.setText("/");
        entre_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entre_btnActionPerformed(evt);
            }
        });
        jPanel3.add(entre_btn);

        btn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel3.add(btn4);

        btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel3.add(btn5);

        btn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel3.add(btn6);

        por_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        por_btn.setText("*");
        por_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                por_btnActionPerformed(evt);
            }
        });
        jPanel3.add(por_btn);

        btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn1);

        btn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel3.add(btn2);

        btn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel3.add(btn3);

        menos_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menos_btn.setText("-");
        menos_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_btnActionPerformed(evt);
            }
        });
        jPanel3.add(menos_btn);

        punto_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        punto_btn.setText(".");
        punto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punto_btnActionPerformed(evt);
            }
        });
        jPanel3.add(punto_btn);

        btn0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel3.add(btn0);

        igual_btn.setBackground(new java.awt.Color(0, 204, 51));
        igual_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        igual_btn.setText("=");
        igual_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igual_btnActionPerformed(evt);
            }
        });
        jPanel3.add(igual_btn);

        mas_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mas_btn.setText("+");
        mas_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mas_btnActionPerformed(evt);
            }
        });
        jPanel3.add(mas_btn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        number_key = "7"; calc();
    }//GEN-LAST:event_btn7ActionPerformed

    private void entre_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entre_btnActionPerformed
        // TODO add your handling code here:
        operation_key = "/"; calc();
    }//GEN-LAST:event_entre_btnActionPerformed

    private void menos_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_btnActionPerformed
        // TODO add your handling code here:
        operation_key = "-"; calc();
    }//GEN-LAST:event_menos_btnActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        number_key = "0"; calc();
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        number_key = "9"; calc();
    }//GEN-LAST:event_btn9ActionPerformed

    private void ce_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ce_btnActionPerformed
        // TODO add your handling code here:
        ce_key = true; calc();
    }//GEN-LAST:event_ce_btnActionPerformed

    private void c_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_btnActionPerformed
        // TODO add your handling code here:
        c_key = true; calc();
    }//GEN-LAST:event_c_btnActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        number_key = "8"; calc();
    }//GEN-LAST:event_btn8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        number_key = "1"; calc();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        number_key = "2"; calc();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        number_key = "3"; calc();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        number_key = "4"; calc();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        number_key = "5"; calc();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        number_key = "6"; calc();
    }//GEN-LAST:event_btn6ActionPerformed

    private void punto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punto_btnActionPerformed
        // TODO add your handling code here:
        number_key = "."; calc();
    }//GEN-LAST:event_punto_btnActionPerformed

    private void igual_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igual_btnActionPerformed
        // TODO add your handling code here:
        equals_key = true; calc();
    }//GEN-LAST:event_igual_btnActionPerformed

    private void por_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_por_btnActionPerformed
        // TODO add your handling code here:
        operation_key = "*"; calc();
    }//GEN-LAST:event_por_btnActionPerformed

    private void mas_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mas_btnActionPerformed
        // TODO add your handling code here:
        operation_key = "+"; calc();
        
    }//GEN-LAST:event_mas_btnActionPerformed
    //* * * S'OLO ALGUNOS DETALLES RELEVANTES EN LA DOCUMENTACI'ON * * *
    /**
     * M'etodo que retorna el resultado de la operaci'on aritm'etica: argument1 (operation) argument2.
     * @param argument1
     * @param argument2
     * @param operation
     * @return 
     */
    private static double result(double argument1, double argument2, String operation){
        switch(operation){
            case "+":return argument1 + argument2 ;
            case "-":return argument1 - argument2 ;
            case "*":return argument1 * argument2 ;
            case "/":return argument1 / argument2 ;
        }
        return 0;
    }
    private void ce_key_process(){
            display2 = "0";
            argument2 = "";operation = "";number_key = "";
            ce_key = false;
            return ;
    }
    private void reset_arg1(){
            display1 = display2 = argument1 = number_key;
            operation = "";number_key = "";
            ce_key = false;
            return ;
    }
    private void c_key_process(){
        display1 = "";display2 = "";sign1 = "" ;argument1 = "";sign2 = "" ;;argument2 = "";operation = "";number_key = "";
        c_key = false;
        return ;
    }
    /**
     * M'etodo que calcula el resultado de la operaci'on (si es posible de realizar). Almacenando la Respuesta en argument1, para
     * realizar calculos consecutivos
     */
    private void equals_key_process(){
        if ((argument1.length() < 1 && "+-.".contains(argument1)) || 
            (argument2.length() < 1 && "+-.".contains(argument2))){equals_key = false;return;};
      double arg1 = Double.parseDouble(sign1 + argument1);
      double arg2 = Double.parseDouble(sign2 + argument2);
      double ans = result(arg1, arg2, operation);
      display2 = argument1 = String.valueOf(ans);
      display1 = "";sign2 = "" ;argument2 = "";sign1="";operation = "";operation_key = "";number_key = "";
      equals_key = false;
      return;
    }
    /**
     * M'etodo que actualiza las variables (llenando las variables): sign1, argument1, operation, sign2, argument1, en el orden correspondiente. 
     */
    private void fill_arg_op(){
       if (operation.length() == 0 ){
            if (sign1.length() == 0 && argument1.length() == 0 && operation_key == "-"){sign1 = "-";
            }
            if (number_key == "." && !argument1.contains(".")){argument1 += number_key;
            }else if(number_key != "."){argument1 += number_key;
            }
       }
       if ("+-/*".contains(operation_key) && argument1.length() >= 1 && operation.length() == 0){
            operation = operation_key;
           
            display1 = sign1 + argument1 + operation;
            display2 = sign1 + argument1;
           
       }else if ("+-/*".contains(operation) && operation.length() != 0){
            if (sign2.length() == 0 && argument2.length() == 0 && operation_key == "-"){sign2 = "-";
            }
            if (number_key == "." && !argument2.contains(".")){argument2 += number_key;
            }else if(number_key != "."){argument2 += number_key;
            }
            
            display1 = sign1 + argument1 + operation;
            display2 = sign2 + argument2;
            
       }
       number_key = "";operation_key = ""; 
    }
    private static String format1(String str,int n){
        if (str.length() == 1 && "+-*/".contains(str)) return "0" + str;
        if (str.length() <= n) return str;
        return String.format("%6.5e", Double.valueOf(str));
    } 
    private static String format2(String str,int n){
        if (str.length() <= n) return str;
        return String.format("%6.5e", Double.valueOf(str));
    } 
    /**
     * M'etodo que muestra los valores en el JLabel, y en el JTextField en el formato adecuado. Aplicando Notaci'on de ingenieri'a,
     * si se excede el ancho del JLabel, y/o el JTextField.
     */
    private void display_1_2(){
        String display1_format = format1(display1.replaceAll("^0*", ""),34);
        String display2_format = format2(display2.replaceAll("^0*", ""),16);
        jLabel1.setText(display1_format);   
        if (display2_format.length() == 0){display2_format = "0";}
        jTextField1.setText(display2_format);
        jTextField1.paintImmediately(jTextField1.getVisibleRect());
    }
    
    /**
     * M'etodo que realiza los subprocesos de la calculadora
     */
    private void calc(){
        if       (ce_key == true)     {ce_key_process();
        }else if (c_key == true)      {c_key_process();
        }else if (equals_key == true) {equals_key_process();
        }else                         {
            if (operation_key.length() == 1 && (argument1.length() > 0 && argument2.length() > 0)){
                String copy_operation_key = operation_key;
                equals_key_process();
                operation_key = copy_operation_key;
                fill_arg_op();
                operation_key = copy_operation_key = "";
            }else if (number_key.length() == 1 && display1.equals("") && argument1.length() > 0){reset_arg1();
            }else{
            fill_arg_op();}
        }
        display_1_2();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton c_btn;
    private javax.swing.JButton ce_btn;
    private javax.swing.JButton entre_btn;
    private javax.swing.JButton igual_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton mas_btn;
    private javax.swing.JButton menos_btn;
    private javax.swing.JButton por_btn;
    private javax.swing.JButton punto_btn;
    // End of variables declaration//GEN-END:variables
}
